eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/
spring:
  application:
    name: ormadmin

liorm:
  # 连接
  url: jdbc:sqlserver://127.0.0.1:1433;DatabaseName=LiSystem;
  #url: jdbc:sqlserver://192.168.1.187:1433;databaseName=LiSystem;
  username: sa
  password: 111222
  #password: Caster00
logging:
  file: mylogs.log
  path: C:/mylogs

person:
  lastName: hello
  age: 18
  boss: false
  birth: 2018/3/3
  maps: {k1: v1, k2: 12}
  lists:
    - lisi
    - zhaoliu

  dog:
    name: 小白
    age: 5


